Extra service branch
OlderLesha/ServiceForWorkingWithStockExchange pull request #7
Opened 2021-12-15 09:46 UTC by OlderLesha

Added extra service, mail sender

2021-12-19 13:32 UTC, AlRezz commented on src/main/java/com/kravchenko/SpringTask/service/RegistrationService.java
> +        mailService.sendSimpleMessage(saveUserDto.getMail(), "Registration", "You have successfully registered on the TrackingService");
А если пользователь не сохраниться?
Получиться, что письмо ушло - а пользователя нет.

2021-12-19 13:33 UTC, AlRezz commented on src/main/java/com/kravchenko/SpringTask/service/SubscriptionService.java
> -//        List<RoleEntity> userRoles=userEntity.getRoles();
не оставляй закомменитрованный код

2021-12-19 13:34 UTC, AlRezz commented on src/main/java/com/kravchenko/SpringTask/service/SubscriptionService.java
>              throw new SubscriptionAlreadyActive(userSubscription.getId().toString());
В чем логика этого блока?

2021-12-19 13:41 UTC, AlRezz requested changes
1. Наименование эндпоинтов, методов и т.д. Избегать имен userBlock. Переписать либо /user/block или /user-block. Почитать https://restfulapi.net/resource-naming/
2. Имена тестов должны объяснять, что тестируется. Есть концепция GWT http://cakebaker.42dh.com/2009/05/28/given-when-then/

2021-12-20 13:03 UTC, OlderLesha commented on src/main/java/com/kravchenko/SpringTask/service/RegistrationService.java
> +        mailService.sendSimpleMessage(saveUserDto.getMail(), "Registration", "You have successfully registered on the TrackingService");
исправил везде

2021-12-20 13:04 UTC, OlderLesha commented on src/main/java/com/kravchenko/SpringTask/service/SubscriptionService.java
> -//        List<RoleEntity> userRoles=userEntity.getRoles();
исправил

2021-12-20 17:30 UTC, AlRezz approved these changes

2021-12-21 07:38 UTC, merged